### ISSUE TITLE
Align on prototyping programming language tradeoffs

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#135]
**Background**
In our scoping discussion today, we talked about potential tradeoffs of prototyping in Django/Python vs FS's lean towards the application potentially using Java and AngularJS. We are using Django/python for prototyping because it allows us to move quickly, but if FS decides on the Java/AngularJS approach, this code wouldn't be reusable by the vendor. This may be fine, we just want to make sure everyone is on the same page about the tradeoffs. 

We should discuss this with technical FS stakeholders and acknowledge this tradeoff, and potentially discuss the benefits and feasibility of using Django long-term.

**We'll know we're done when...**
- [x] We have alignment on the tradeoffs and consensus on how reusable our prototypes will be in the long-term. 

**Tasks**
- [x] From Neil - talk to Steve Lammey
- [ ] Document our technical decisions on the Wiki for NRM/CIO transparency

**Comment by allisonnorman** [comment]
@tbaxter-18f @neilmb - Feel free to add more context or update this if I haven't captured all of the nuances you brought up.

**Comment by neilmb** [comment]
Meeting originally scheduled for today was postponed until next week.

**Comment by neilmb** [comment]
The meeting happened today. The sentiment was just to document our decision-making and keep Steve Lammey and Heather Busam in the loop so that they can deal with anything they have to at the CIO level.

Initial documentation of this project's decision-making process is here https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Platform-and-Technologies

@allisonnorman @tbaxter-18f Can you take a look at that page and make edits as you see fit? After that, I think that we will have done what we need to do here.

**Comment by allisonnorman** [comment]
LGTM!
