### ISSUE TITLE
Track AWS Skynet dependency

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#148]
**Background**
Based on [Neil's meeting](https://github.com/18F/NRM-Grants-Agreements/issues/120) with Matt Reis and Aaron Burk, we learned that the AWS environment, called Skynet, will be available after 4/30/21. This is an important dependency to track over the next few weeks to ensure we continue to track their progress and ensure the environment will be ready in early May. 

**We'll know we're done when...**
- [x] We have access to the AWS dev environment and can begin migrating our prototype to that environment. 

**Tasks**
- [x] Send Aaron Burke and Matt Resiss names and details for folks who will need access to Skynet so that they can get a jump on setting it up and are ready to hit "go" the moment the landing zone is ready
- [x] Check in with Matt Reiss and Aaron Burk every 1-2 weeks to ensure the OpenForest move to Skynet is on track, and that we are still on track to get access to a dev environment immediately after.
- [ ] Note: When we are ready to connect up to the NRM databases in staging and production Skynet environments, then we may need to update the Privacy Threshold Analysis (PTA) and Privacy Impact Assessment (PIA) because we will be accessing PII. Once we have access, we can create issues for Skynet setup but don't want to lose track of this step.

**Comment by neilmb** [comment]
Checked in with Matt Reiss today. He said that the OpenForest transition to Skynet is on track for 4/30 which puts us on track for getting access soon after that.

**Comment by neilmb** [comment]
We transferred the github repo to the USDAForestService organization. They are setting up the CI pipelines on jenkins.fs.usda.gov and SonarQube results on sca.fedgovloud.us.

**Comment by neilmb** [comment]
The CI pipelines are up and running on jenkins.fs.usda.gov and sca.fedgovcloud.us.

**Comment by neilmb** [comment]
Had a meeting this afternoon with the FS Cloud Foundation team and finally got to talk with the people who are doing the actual implementation. They suggested end of the week or early next week for having the actual FS dev environment set up. Tracking issue on their end is https://code.fs.usda.gov/forest-service/CIO-Cloud-Foundation/issues/77

**Comment by neilmb** [comment]
The app is up and running in the FS AWS environment now http://ga-development.eba-c5v3ebxp.us-gov-west-1.elasticbeanstalk.com/

I'm going to consider this done. We still have work to do getting used to developing in the environment, but we have the setup that we need to do that.
