### ISSUE TITLE
Track contracting situation

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#151]
**Background**
We have a few moving pieces around the acquisition timeline we need to track. Let's use this issue to track deadlines, open questions, etc. 

Open questions:
- [x] What is the timeline and decision framework around the acquisition strategy and backup options? (plan A (RFQ/solicitation), plan B, plan C?)
- [x] When can we publish the RFQ? (and how does the 4/1 deadline impact the ability to do that?)

Related issues:
- Get CO assigned (#97) (closed as dupe)
- Publish draft RFQ for comment (#103)

**We'll know we're done when...**
- [x] We have alignment with stakeholders and have a path to awarding a contract and starting module 1. 
- [x] We have a CO assigned
- [x]  We've talked with the CO or contracting team and understand overall timelines and processes we need to follow for the RFQ and awarding a vendor contract for module 1.

**Tasks**
- [x] Document options in the event we don't have necessary approvals in place to post RFQ under contracting  deadlines, including risks pro/cons and key decision points / dates decisions needed. 
- [x] Circulate for the team to review
- [x] revise based on feedback
- [x] share w/ weekly ship

**Comment by MelissaBraxton** [comment]
Do we still think acceptance criteria 2 and 3 make sense here? Given how the situation has changed, maybe we drop them in a new issue if need be? @neilmb and @MCHopson?

**Comment by neilmb** [comment]
I think that they are actually both satisfied. We have a CO assigned, as much as we are ever going to get, and we have talked with them and understand the timeline and processes (mostly).

**Comment by MelissaBraxton** [comment]
@neilmb  - Can I hand this one off to you at this point? Since you're in more meetings than me, you might be best positioned to know when we can check off the acceptance criteria.

**Comment by MelissaBraxton** [comment]
I think our [new doc](https://docs.google.com/document/d/1uU-JcYNfsYq75WigW0zmMzPU-ZMV5JHwkd_HWxC64Uc/edit#) is an extension of this. Self-assigning and moving back to in progress.

**Comment by neilmb** [comment]
This [doc](https://docs.google.com/document/d/1uU-JcYNfsYq75WigW0zmMzPU-ZMV5JHwkd_HWxC64Uc) was sent to Heather, Aaron, and Jay yesterday.

**Comment by neilmb** [comment]
Feedback from Aaron, Jay, and Heather was to not pause and possibly work on through calendar 2021 after a modification of our agreement. We will need to plan our priorities for this situation.
