### ISSUE TITLE
Scope feasibility of importing financial tables for customized dashboards and approval workflows

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#155]
**Background**
We are exploring opportunities to de-risk electronic agreement creation by doing some prototyping work in our E&I. More details can be found in #152 around how this fits into a broader strategy of de-risking. Here are the relevant user stories we're focusing on:
- As a Program Manager, I need to be able to electronically create and submit a proposal that's complete and compliant in order for it to be reviewed by the budget team for commitment approval. #184
- As a Budget Approver, I need to see commitment requests from a new proposal that are ready for my attention so that I can approve them. #169

As part of this, we want to continue to iterate on the proposal creation form and personalized dashboard prototype. Based on usability testing insights, and our goal above, we will want to find opportunities to iterate to validate our hypothesis that we can import financial tables and other data, and that we feel confident that we can leverage the existing FMMI integration in module 1. 

**Our hypotheses**
- We won't need a new integration with FMMI until we are ready to move off of Oracle completely
- We can support the modification review and approval workflow without a new FMMI integration

Relevant documentation:
- Here is a [draft workflow model](https://app.mural.co/t/gsa6/m/gsa6/1617302710083/284af01bd7dec812ac7013275a7767d1a99693ee) that Melissa has been working on, where integration with FMMI comes into play in these two user journeys. (Relevant issue: #162)

**We'll know we're done when...**
- [x] We have a sense of what kind of work it will take to de-risk this FMMI integration assumption. 
- [x] We have ideas on how we could demonstrate this feasibility in the leanest way to validate our hypothesis. 
- [x] We've documented what we've learned. 

**Tasks**
- [x] Create issues based on what's next based on the feasibility. 
- [x] Meet with Jamie to hear about how the current FMMI integration works and what is hard about it.
- [x] Meet with Thompson to hear the details on how transactions come from FMMI and get sent to FMMI (bidirectional).

**Comment by neilmb** [comment]
Met today with Thompson Grant and Allison Leach from NRM's dev team. There is an "Outbound" process (that is outbound from FMMI to NRM) and and "Inbound" process (that goes inbound to FMMI from NRM). The documentation for those interfaces is here https://drive.google.com/file/d/1R2KwZIisJ5Yc3w-LMqrj8rxjRVE8wQkt and here https://drive.google.com/file/d/1wURxIqzTs9xvc2x2wJ10SQtp2-oPXDpj

For the outbound process, once per day in the morning (5am?) an oracle job gets a file from the FMMI SSH dropbox, then hands that data to another oracle package that writes the data eventually into the II_GA_DAILY_TRANS table.

For the inbound process, once per day in the evening (8pm?) an oracle job goes through the G&A database and finds records that have changed that day and prepares a file and then uploads that file to the FMMI SSH dropbox.

**Comment by neilmb** [comment]
It appears feasible for us to work directly with the daily transaction table and rely on the ongoing interface process with FMMI to do the data import. We will need to decide on some tasks to de-risk our work with this. In the current prototype, that means importing the transactions table and figuring out how to display the data on a details page, or a relevant display. And in a later stage once there is a connection to the staging database, we should experiment with writing financial records into the database and monitoring how the go to FMMI and back again.

**Comment by neilmb** [comment]
Met with Jamie and Melanie. They emphasized that there are still mismatches between what they send and what comes back from FMMI on the outbound job. Melanie spends 1/2 hour every day reconciling the easy ones. Jamie handles the harder ones which arise when Treasury pays a bundle of invoices in a single transaction that need to be disaggregated to the correct places in the NRM system. There are still problems with the IAA part of the FMMI interface which wasn't completed when the FMMI interface was built in 2012.

**Comment by allisonnorman** [comment]
@neilmb Couple questions:
- Do you know how this cleanup from Jamie and Melanie happens? If there's a mismatch between what they send initially and what comes back, what do they do that ultimately fixes it? 
- [Depending on the answer to the above question, if relevant] Do you have a sense of whether the cleanup Melanie and Jamie do gets reflected back in the transaction table? (i.e. would we be able to benefit from that cleanup?)

**Comment by neilmb** [comment]
> * Do you know how this cleanup from Jamie and Melanie happens? If there's a mismatch between what they send initially and what comes back, what do they do that ultimately fixes it?

They have built a UI in the legacy G&A app that allows Jamie and Melanie to take transactions that don't match and edit the way that they will be imported back into the app.

> * [Depending on the answer to the above question, if relevant] Do you have a sense of whether the cleanup Melanie and Jamie do gets reflected back in the transaction table? (i.e. would we be able to benefit from that cleanup?)

Yes, transactions coming from the FMMI outbound process get logged back into the daily transactions table after they are manually corrected, so as long as that legacy process continues, our new app would benefit.

**Comment by neilmb** [comment]
@cmajel opined that the appearance of a new commitment in the budget approver's workflow is probably the easiest place to demonstrate that we can actually make use of this financial data. However, it will be hard to test in our dev environment because we won't have the daily outbound data getting loaded back into the system to watch how it happens. It could more easily be tested in a unit/integration test where we add a commitment to the database table and check that it looks right in the UI.
