### ISSUE TITLE
Prepare materials for IRB meeting presentation

### ISSUE THREAD

**Issue by neilmb** [USDAForestService/NRM-Grants-Agreements#160]
**Background**
The CIO's IRB meets in late April to decide on a technical path forward for G&A and re-direct the ezFedGrants funding to NRM. We need to work with Jay to develop a written proposal and powerpoint presentation for them.

**We'll know we're done when...**
- [x] The presentation happens on May 26th

**Tasks**
- [X] Prepare a Powerpoint for the IRB presentation
- [x] Make updates to presentation
- [x] Prep for dry run
- [x] Consider preparing a one-page brief to go along with the presentation

**Comment by neilmb** [comment]
Sent a first draft back to Jay so it can be reviewed by Chris, Robert, and Heather.
