### ISSUE TITLE
Determine what changes an agreement's status from created to approved

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#176]
**Background**
We know from the user guide that status is not an editable field. What we don't know is what makes status change. Since it's non-editable, there must be some combination of events that happens that makes it change. What are they?

**We'll know we're done when...**
- [x] We know what conditions trigger a status change
- [ ] We have either implemented those checks in our own code, or have logged an appropriate follow-up story to do so.

**Tasks**
- [ ] 
- [ ]

**Comment by MelissaBraxton** [comment]
Draft Mural that shows this is [here](https://app.mural.co/t/gsa6/m/gsa6/1617302710083/284af01bd7dec812ac7013275a7767d1a99693ee)

**Comment by MelissaBraxton** [comment]
@tbaxter-18f  - What do you think about this as useful format for tracking this info? 
<img width="1183" alt="Screen Shot 2021-04-20 at 2 35 30 PM" src="https://user-images.githubusercontent.com/20651166/115467097-d353cf80-a1e5-11eb-86ea-01a40ef5a824.png">

I likely wont have bandwidth to fill this out this sprint.

**Comment by tbaxter-18f** [comment]
I think if it's helpful to help sort it out and track it, cool, but for me I'd like to see the output of this be issues logged for each state change outlining what has to happen for it to flip. So something like:

## Make status change to PROP_ACCEPTED

We would like the agreement status to change when the following conditions are met:
* Valid Agreement number has been entered
* Program responsibility type is populated from WPAP

And so on. I just made those conditions up, but whatever the real ones are, we can make a checklist of them as acceptance criteria.

**Comment by cmajel** [comment]
I can take a pass at this based on what we learn at today's walkthrough with Jay. Right now, our to be model and figma are envisioning a process that gets a proposal to `prop_approved`, and a commitment to `new commitment`.

**Comment by MelissaBraxton** [comment]
After today's co-working, I'm thinking the most usaful thing to focus on here is what the to-be min. requirements are to move something from NEW > GA_PENDING. What do you think, @cmajel?

**Comment by cmajel** [comment]
Recapping our chat from design/dev sync, we talked about...
* How the [workflow mural](https://app.mural.co/t/gsa6/m/gsa6/1617302710083/284af01bd7dec812ac7013275a7767d1a99693ee) has about 90% of the info we need, but a spreadsheet view may be helpful.
* That it's useful to note data that's needed, as well as which roles are taking actions.
* That we probably won't get everything documented completely perfectly, and we'll learn by trying. 
* But, that after this next round of usability testing, we should know enough to give more structured guidance on what will trigger state changes in a new workflow.
* That we should think about how dev/design uses the same language to talk about these fields, and think about how design guidance will map to the[ form model](https://github.com/18F/NRM-Grants-Agreements/blob/d0d6a9166480c10f840e334aa0a563c1c4ec4dd5/nrm_django/grants/forms.py) dev is building. 

I see the next step to be providing state guidance after we get feedback on this new workflow through usability testing. @neilmb and @MelissaBraxton feel free to add anything I missed.

**Comment by MelissaBraxton** [comment]
@allisonnorman 

Link to the [sheet pictured above.](https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=1989925752)

Christine and Carter also worked on [this Mural](https://app.mural.co/t/gsa6/m/gsa6/1620144100658/7c9b5ee4140b909712ecfb37bdf8c9b3957e4acc) as another way to get at it. 

We can look at both together on Wed.!

**Comment by allisonnorman** [comment]
Progress so far:
- [X] translated [all participating agreements ](https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=0)sheet to [PA data by state](https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=1989925752)
- [X] Created a new view to show [fields by tab](https://docs.google.com/spreadsheets/d/1wIktie0mGYUnC19ZdtcAeXrFV2ROYA_bR2VPyYVM7jI/edit#gid=489551622) to show duplicative fields and various states as they go through the workflow

**Comment by MelissaBraxton** [comment]
@tbaxter-18f  - I know you have _some_ issues you've already created that are follow ups to this. Looking at our acceptance criteria, can I assign this to you to make sure we have issues for any other next steps you foresee and close this out?

**Comment by tbaxter-18f** [comment]
Sure!

**Comment by tbaxter-18f** [comment]
I've logged #268, #269, and #270, which get us out through prop_approved at least. I think that should keep us busy for awhile and we can probably close this out for now.
