### ISSUE TITLE
As a Program Manager, I need to be able to electronically create and submit a proposal that's complete and compliant in order for it to be reviewed by the budget team for commitment approval.

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#184]
**Notes**
This is a user story for our proposal creation de-risking work, that ultimately ties into #169. This story is focused on creating a proposal and attaching the commitment, and #169 is related to surfacing this need to approve via a dashboard. 

We will be focusing on outgoing funds, and we will focus in on a subset of instrument types. Initially, we will start with participating agreements because it's the most commonly used instrument type (~815 agreements annually). 

**We want to validate the following assumptions:**
- [Design hypothesis] Putting new agreement / new proposal forms online will help reduce errors / improve consistency
- [Design hypotheses] Encoding the decision tree into the online agreement creation process will reduce effort and errors assoc. with folks choosing the wrong agreement type
- [Technical assumption] Using the new online agreement form to create a new record in the DB will be easy
- [Technical assumption] We will be able to import financial tables and other data needed to tie a commitment to FMMI.
- [Technical assumption] We wont need a new integration with FMMI until we are ready to move off of Oracle completely.
- [Technical assumption] We can support the modification review and approval workflow without a new FMMI integration.
-  [Technical assumption] We think we can achieve automatic closeout without touching the FMMI integration.

**We would like to explore de-risking the electronic agreement creation and approval workflow, potentially in the following ways** (though prone to change as we explore):
- We could extend the proposal creation prototype to support a workflow for budget approvers approving a commitment based on FMMI (commitment pending --> commitment approved / FFIS processed, from FMMI)
- Submitted form data writes to the db.

**We'll know we're done when...**
- [ ] PO has approved and accepted changes relevant to this user story
- [ ] We have de-risked the technical hypothesis that we can consume the necessary data necessary for the proposal form (required fields) and write to the database, and that a proposal would be ready to surface to Budget Approvers for approval (#169). When we're done, we should feel confident that expanding this work to other instrument types is feasible by a vendor team.
- [ ] We've tested this with users.
- [ ] We've created relevant documentation for the vendor team.

**Supporting documentation**
- Scope agreement creation and approval workflow prototyping #152 (general goals and assumptions)
- [Field audit sheet](https://docs.google.com/spreadsheets/d/1szcS652FZohhxkSPMNGnkPrj06uxSKqvC3ClL83ngsk/edit#gid=1044564396)
- [Draft pre-award approval workflow ](https://app.mural.co/t/gsa6/m/gsa6/1617302710083/284af01bd7dec812ac7013275a7767d1a99693ee)

**Related issues**
- Mock up a new agreement creation form #153
- Submit a form that writes to the sandbox db #154
- Plan next user research focus area #171
- Mock up an agreement creation form for budget approver story #173
- Implement the proposal form mocks in our prototype #172

**Open questions**
- [X] Which subset of instrument types could we focus in on for de-risking purposes? - Participating agreements = PA

**Tasks**
- [ ] Determine what tasks are necessary to complete this issue.

**Comment by allisonnorman** [comment]
In ZH, we can use this to summarize the agreement creation epic and close the issue. Keeping this until we switch over.

**Comment by tbaxter-18f** [comment]
@allisonnorman do we still need this? It definitely *feels* like an epic.

**Comment by allisonnorman** [comment]
Yeah, good call. I meant to use this as the epic description for agreement creation but lost track of it. Going to do that now. Thanks!

**Comment by allisonnorman** [comment]
Closing this as I've moved the description to the agreement creation issue (#253)
