### ISSUE TITLE
Migrate grant creation update off built-in admin views

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#189]
**Background**
At this point we've customized the built-in admin auto-created views to the point where we're stretching their limits. It would (we think) be clearer and easier to maintain if we overrode the built-ins and just built our own. 

**We'll know we're done when...**
- [ ] Existing admin-based forms are replaced with a more typical model-view-template architecture 
- [ ] We have confirmed adding a grant works correctly
- [ ] We have confirmed updating a grant works correctly
- [ ] We have added any necessary context that the admin view provides into our view and template
- [ ] Navigation between our view and remaining admin views is seamless.

**Tasks**
- [ ] 
- [ ]
