### ISSUE TITLE
Implement a FS USWDS theme 

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#190]
**Background**
We want the new G&A to follow Forest Service branding and style guidelines. We'll want to create a FS theme for the [US Web Design System](https://designsystem.digital.gov/), and ensure design and dev are working from the same styles.

Note: We should consider when we want to invest in higher fidelity work, when lower fidelity work can help us derisk quickly.

**We'll know we're done when...**
- [ ] Mocks have FS branding
- [ ] Live prototypes have FS branding
- [ ] Design and dev are using the same theme elements for their work (typographic, color, spacing)

**Tasks**

- [ ] Review web style resources from #105 
- [ ] Document which styles we need to include in mocks and the prototype
- [ ] **add more as needed**

**Resources from #105** 
   - [USWDS theme files](https://drive.google.com/drive/folders/1RSHOk2USWiJxqq1mOmfbSDb9XmLR8W6T) from https://www.fs.usda.gov/
   - [Automated styleguide](https://cms.fs.usda.gov/simple-styleguide) via Drupal from fs.usda.gov (requires FS VPN)
   - [USFS Digital playbook by EAD](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/), uses USWDS1 (requires FS VPN)
   - [Notes from conversation](https://docs.google.com/document/d/1U-Auozuf2XSIHHdi6NPK7X7FjqIxNeEe6SuDq4zamEI/edit#heading=h.xn5wobrdvd1y)
   - [Forest Service style guide and branding guidelines](https://usdagcc.sharepoint.com/sites/fs-wo-oc/SitePages/Visual-Standards-Home.aspx) (requires FS VPN)

**Comment by allisonnorman** [comment]
I'm closing #131 as a stale issue, but there are some small tweaks noted there to better use USWDS from there I want to make sure we don't lose, if still valid as part of this issue:
-  paginator colors are wrong. Can we uswds-ify it, or at least get the colors right?
- What is the difficulty of changing icons over to USWDS versions? Are they available?

**Comment by cmajel** [comment]
Recapping a chat with @MelissaBraxton, using USWDS form components and pulling in the [USWDS theme files](https://drive.google.com/drive/folders/1RSHOk2USWiJxqq1mOmfbSDb9XmLR8W6T) from https://www.fs.usda.gov/ may be a good place to start.

Some of the form components we used in the mocks include:
* Step Indicator
* Button
* Dropdown
* Date picker
* Combo box
* Text input 
* Radio buttons
* Table

**Comment by MelissaBraxton** [comment]
Going to start w/. a microrequest for a product designer or visual designer to pair w/ Carter on this.

**Comment by MelissaBraxton** [comment]
@austinhernandez - Links for you:

[Mocks in Figma](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=325%3A0)
[Mocks in InVision, JIC](https://gsa.invisionapp.com/console/share/9610WO0NRF7V/619008507)
[Django prototype]( ga-development.eba-c5v3ebxp.us-gov-west-1.elasticbeanstalk.com/admin) 

@tbaxter-18f can you set Austin up with a name & password for the Django prototype?

**Comment by austinhernandez** [comment]
@tbaxter-18f is this ok?

![2021-06-02-14-50-fs-nrm app cloud gov](https://user-images.githubusercontent.com/23194720/120546468-edc0c180-c3bd-11eb-9e36-d805ef6eae49.png)

Form code: 
https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/form.html

Date picker: 
https://designsystem.digital.gov/components/date-picker/

**Comment by tbaxter-18f** [comment]
I think it's great and if I have any questions I'll follow up with you when you're back next week. Thank you!

**Comment by tbaxter-18f** [comment]
@austinhernandez  Trying to capture some comments above, when you're back could you look into (if you haven't already) 

* paginator colors are wrong. Can we uswds-ify it, or at least get the colors right?
* What is the difficulty of changing icons over to USWDS versions? Are they available? (this one should be very doable if we just ID which icons to swap)
* Anything we may need to do for these form components we're not doing already 
Step Indicator
Button
Dropdown
Date picker
Combo box
Text input
Radio buttons
Table

thank you, and let's sync up again Monday or Tuesday!

**Comment by austinhernandez** [comment]
- Use button default colors for paginator and uswds style! ([heres the pagination](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/button-groups.html))
- What is the difficulty of changing icons over to USWDS versions? Are they available? Not sure how challenging it is to switch these over but the Check and X, !, and ? icons should suffice.
- Step Indicator - https://designsystem.digital.gov/components/step-indicator/ ([use these colors](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/button-groups.html))
- Button - https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/button.html ([use these colors and spacing](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/button-groups.html))
- Dropdown - https://designsystem.digital.gov/components/dropdown/ (just keep it as is but the font should change)
- Date picker - https://designsystem.digital.gov/components/date-range-picker/
- Combo box - https://designsystem.digital.gov/components/combo-box/
- Text input - https://designsystem.digital.gov/components/text-input/
- Radio buttons - https://designsystem.digital.gov/components/radio-buttons/ ([use these colors instead of blue](https://code.fs.usda.gov/pages/forest-service/Forest-Service-Digital-Playbook/button-groups.html))
- Table - https://designsystem.digital.gov/components/table/ (these should be good, just change the font)

**Comment by tbaxter-18f** [comment]
I think for the scope of this issue it's resolved with https://github.com/USDAForestService/NRM-Grants-Agreements/pull/305 but I also expect integration and refinement to be ongoing, and there should be follow-up issues where we spot specific things we'd like to improve (like combo box, which is logged separately)

**Comment by MelissaBraxton** [comment]
@tbaxter-18f  - Sounds like we can closer this then?

**Comment by tbaxter-18f** [comment]
Yup
