### ISSUE TITLE
Create sprint 6 research plan

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#191]
**Background**
We'll likely focus this round of research on the agreement creation process. 

**We'll know we're done when...**
- [x]  We have a research plan for our next usability study, that captures key research questions that will inform prototype design and development.

**Tasks**
- [x]  Draft design hypothesis/es
- [x] Write up research Qs
- [x]  Prioritizing questions for research plan
- [x]  Write interview protocol
- [x] Create artifacts/probes for testing
- [x]  A day or two before the first test, assess research Qs against artifacts /probes for testing
- [x]  Refine research probes / research protocol until they're aligned
