### ISSUE TITLE
Schedule sprint 6 usability tests

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#192]
**Background**
We want to test sprint 6 design hypotheses with users and get feedback on early prototypes. 

**We'll know we're done when...**
- [x] We have scheduled 5-7 usability test sessions with users.
- [x] All participants are NFS program managers
- [x] We've included relevant stakeholders to listen in on tests

**Tasks**
- [x] Email Jay and Jamie for more contacts
- [x] Send out invitations 
- [x] Add things to the calendar

**Comment by allisonnorman** [comment]
@MelissaBraxton - Closing this as we have enough participants for this round and have met the DoD. Feel free to reopen if you feel like there's more to it.
