### ISSUE TITLE
Write up sprint 6 research insights

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#193]
**Background**

**We'll know we're done when...**
- [x] insights are documented in wiki [link](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/User-research-report-Sprint-7,-May-2021)
- [x] refinements are documented as user stories 

**Tasks**
- [x] Synthesize
- [x] Write up
- [x] Get one other person on team to review
- [x] Post to wiki
- [x] Add user stories to user story sheet (for #166)

**Comment by MelissaBraxton** [comment]
Report shaping up [here](https://docs.google.com/document/d/1o0iY7hgAk6qASKW96Vl6Y7jmB-Dra-ElNajT2l5I6JA/edit#).
