### ISSUE TITLE
Create new issues from transition plan

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#197]
**Background**
We'll want to make sure we're trackiong transition tasks alongside other work to ensure we'll meet our transition goals. We've listed these tasks in the transition plan doc, but there's a bit of translation into new issues that will need to happen. In some cases, it'll make sense to combine a few tasks from the transition plan under the same GitHub issue. 

**We'll know we're done when...**
- [x] We have reviewed the transition plan as it stands and created (and cross-referenced) appropriate Github issues.
- [x] We made a note in the transition plan that new tasks added in the doc should also be added in Github

**Tasks**
- [x] Review the doc https://docs.google.com/document/d/1YOlrpQXbbWwYcE-LYeqoavvMDolHjIgBmfQorp8Ft3c and make new issues for tasks, or link tasks to existing issues.
