### ISSUE TITLE
Work with Jay to strategize socializing the product roadmap with stakeholders

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#199]
**Background**
Building on #39 and #150, we need to think about how and with whom we share the roadmap to ensure stakeholders and project sponsors have an opportunity to provide feedback. 

Open questions:
- Who needs to see this?
- What is the best format to share (send wiki, present, etc)

**We'll know we're done when...**
- [ ] We know next steps for how to socialize the roadmap and next phase of work. 

**Tasks**
- [X] Sync as a team on a strategy
- [X] Pair with Jay to plan on how to present this information
- [X] Set up meetings or find venues to share out the roadmap strategy (see #272)

**Comment by allisonnorman** [comment]
Started drafting some notes [here](https://docs.google.com/document/d/1ZqjYrNmt7nW2OymOXeaYuzXgtf34OPWvhv4ka_qe1vM/edit#heading=h.iua7az3hzhp) re: a workshop agenda.

**Comment by allisonnorman** [comment]
I've talked with Jay and he's on board for socializing the strategy and roadmapping work within the kick-off. I created #272 and #273 to focus on that.
