### ISSUE TITLE
Refine proposal creation mockups for next usability test

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#204]
**Background**
We explored a new workflow (#162) and mocked up a stepped proposal creation experience (#173), and want to get feedback from folks who create proposals. This ticket is to refine the mockups to align with the research plan, and to incorporate feedback from our last session with G&A staff.

**We'll know we're done when...**
- [ ] We have mockups that represent our proposed workflow that can be shared with participants.

**Tasks**
- [ ] Define key research questions (#191) so that the mocks can be adjusted to that scope
- [ ] Meet with G&A staff again to validate that we've captured their feedback accurately. 
- [ ] Mocks are in a form that can be shared with participants (Invision, PDF).
- [ ] What else...

**Comment by cmajel** [comment]
This has been completed and was a part of our usability tests last week 🎉 

[Invision link we tested](https://gsa.invisionapp.com/share/9610WO0NRF7V#/451166352_Ac5--create--01-Dashboard)
To-be workflow we followed #162 

This iteration explored a few things, including:
* Combining proposal creation, program approval and commitment creation into one form
* Breaking proposal creation into a multi-step form that includes:
  * Project overview (basic project information, and agreement details)
  * Partnership details (FS office and cooperator info)
  * Agreement team (as is known, who will be working on this)
  * Commitments (opportunity to add workplan acquisition ID and commitment information)
  * Review and submit (review information provided, and sign off on program approval of the proposal and commitment, and route for budget approval)
* Starting to add more `decision-tree-like` questions to proposal creation so that GMSs have more on the shape of the agreement when they are reviewing it. 
 * Making workplan linkages optional and not a requirement to create a proposal. We did this based on discussions that Workplan's data can be very drafty, and Workplan is more familiar to budget approvers than program managers who often create the proposal. 
 

Open questions:
* What changes, if any, should be made to encourage even earlier collaboration between GMSs and PMs within the G&A application? 
* How do budget approvers get notified of a commitment request, review it, and approve or reject it?
* How do we identify what additional information a GMS needs to fill out to complete policy requirements?
* Do we provide the opportunity for PMs to share draft agreements and financial plans within the system? If yes....
  * What do people using G&A need to manage and collaborate on these documents effectively? 
  * What information, if any, moves to electronic formats, and what remains in PDF/document formats?
