### ISSUE TITLE
Refine dashboard mockups for next usability test

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#207]
**Background**
We did [initial research on an individualized dashboard concept](https://github.com/18F/NRM-Grants-Agreements/wiki/User-research-topline-----Sprint-3,-March-2021) and have continued to think about how the dashboard could be a launchpad for proposal creation (#173). We have an initial wireframe for updated dashboard changes, but there are additional refinements that are needed, including:
* How proposal creators find the right workplan to start the proposal creation process
* How we distinguish between proposals, agreements and modifications
* How we distinguish between items assigned to you (aka, I am the program approver on this agreement) and items of interest that I want to track (aka, I want to track agreements for my forest)

**We'll know we're done when...**
- [x] We have a mockup that we can share with participants
- [ ] 

**Tasks**
- [x] Cross check current mockups with research questions in #191 
- [x] Adjust mockups as needed
- [x] Make sure mockups can be accessed by participants (Invision, PDF)
- [x] What else...

**Comment by cmajel** [comment]
This work has been started in [Figma](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=536%3A275). Some of the ideas we've included in here are:

* Creating one list of all agreements a person is interested in
  * "Interested in" means agreements a person is assigned to, or that they have said they wanted to watch
* Using a card layout rather than a table layout, which allows us to adjust views and actions based on status
* Identifying some initial filters for navigating the list
* Experimenting with a card layout that...
  * Shows the status and region
  * Shows watch status
  * Shows basic information about the proposal based on status and what information is available (ID number, project title, cooperator, org, start and end date, total funds / available funds)
  * Shows a preview of actions based on state. For example
    * If in approval, shows which step is done and by who
    * If active, shows post award actions
    * Provides access to quick actions to assign team members / contact FS
