### ISSUE TITLE
Revise roadmap and framing docs based on Jay's feedback

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#213]
**Background**
@jayrbergjr has shared some feedback in the [framing doc](https://docs.google.com/document/d/1k-lgrzYcLBtq4uSNirK5Umh5prYGUvglhp7ni_NdkZE/edit?ts=60889687#heading=h.2wa262j0ikqf). We've talked through his feedback but need to ensure we update the framing doc and roadmap accordingly.

**We'll know we're done when...**
- [X] Updates have been published to the wiki.
- [x]  Updates are reflected on Mural roadmap.

**Tasks**
- [x] Make updates in google doc. 
- [x] Publish updates to wiki
- [x] Add early draft collaboration to M1-M3 with Jay and update Mural roadmap.
