### ISSUE TITLE
Figure out how to run prototype under AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#215]
**Background**

FS CIO is proposing AWS Elastic Beanstalk for running the prototype application. It is a PaaS at a similar level to our existing technology.

We should figure out how to get our code running under that platform. If FS accounts are not available soon, there is a `tts-sandbox` AWS account that could be used for this experience. 

The availability of FS AWS is tracked on #148 which covers our dependency from the FS Skynet team.

**We'll know we're done when...**
- [x] We can run our app under AWS Elastic Beanstalk, at least up to getting errors messages from when the code starts running and can't access a database that doesn't exist.

**Tasks**
- [x] Review documentation at https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html et seq.
- [ ] Do a PR adding the required configuration.

**Comment by neilmb** [comment]
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-django.html for configuring Elastic Beanstalk to deploy a Django app with WSGI and choosing Django settings.

**Comment by neilmb** [comment]
The app can be deployed to elastic beanstalk and gives the expected errors on startup because it doesn't have access to a database.

![Screen Shot 2021-05-12 at 11 00 34](https://user-images.githubusercontent.com/443389/118011852-10f3d600-b316-11eb-972a-99835e935729.png)

There is a branch at https://github.com/USDAForestService/NRM-Grants-Agreements/compare/beanstalk but it's not ready for a PR yet because it targets our tts-sandbox AWS environment rather than the FS environment.

**Comment by neilmb** [comment]
Database configuration docs are at https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-rds.html#python-rds-connect

**Comment by neilmb** [comment]
And https://github.com/kgoedecke/circleci-beanstalk-example/blob/master/.circleci/config.yml as an example of deploying from CircleCI.
