### ISSUE TITLE
Prepare for CIO presentation

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#216]
**Background**
Let's pre-synthesize/prep for what we will need to cover with the CIO. The goal of this preso is to emphasize the modular approach and our recommendation. 

**We'll know we're done when...**
- [x] We have presented to the CIO and they have what they need to make a determination on the modular approach. 
- [ ] 

**Tasks**
- [ ] Prep for presentation (what is important to cover? Modular vs COTS, governance decision, how can we push for a decision?)
- [ ] Create an outline. 
- [ ] Create deck
- [ ] Meeting is scheduled

**Comment by neilmb** [comment]
I think that this meeting isn't going to happen and that the CIO has all of our materials that they need to make a decision. I'm confirming that with Heather right now on Teams.

**Comment by neilmb** [comment]
The CTO has made the decision to approve the modular approach.
