### ISSUE TITLE
Start building a "start here" guide

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#217]
**Background**
We know we will need to tie up our work nicely in a bow given that the vendor timeline is fuzzy at this point. Let's start planning this out and identifying what this will look like, and what we can start documenting now. 

Prompt: Imagine the vendor starts in the future, what should they and the FS team look at on day 1 to orient themselves to the work we've done already?

**We'll know we're done when...**
- [x] We have a framework for documenting what's in our heads now, and a plan for how to continue to add to it (i.e. adding documentation to DoD for other issues)

**Tasks**
- [X] Start cataloging what we've done already
- [X] Identify what else may need to be documented
- [X] Create issues, or additional tasks.

**Comment by MelissaBraxton** [comment]
We made [this ](https://docs.google.com/document/d/1tTqv4SupyHYbt14RH7UIRm1ZQbAHeg0SD7ydYlyVlfk/edit#heading=h.483tqfnk843o)for our firewood project, and it worked pretty well in helping us spin things up again when the time came. Just one example of a possible format.

**Comment by allisonnorman** [comment]
I spun this up based on the timber example and added a couple things based on what we have now: [link](https://docs.google.com/document/d/1VcitXr5MZ1J6_EcMk4WSJYtz6VchxtigxsSliaCE49k/edit#)

I think we can likely close this for now after sharing with the team. Open questions:
- How do we want to approach this now? 
- How helpful is this until we know a wrap up date?

**Comment by allisonnorman** [comment]
Much of this is dependent on current state as we prep to hand off, which is arguably not ideal to do today unless we are prepping for a pause. I created #247 which will help define our timeline and if/when to begin documenting.
