### ISSUE TITLE
SPIKE: test alternative subject lines for NRM notifications

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#218]
**Background**
We've learned that there's an opportunity for the notifications that NRM currently sends to better guide people to act on the subject of the notification. To this end, we want to help NRM G&A staff refine the subject line of these messages. This work could also be a good opportunity for some of our partners at NRM to get involved in some of the research and get ideas on how they might do similar activities to test out possible changes after 18F is gone. 

**We'll know we're done when...**
- [ ] We've delivered evidence-based recommendations on changes to the NRM subject lines
- [ ] 

**Tasks**
- [ ] Draft research plan
- [ ] Collect data
- [ ] Synthesize data
- [ ] Write up insights
- [ ] Share insights with partners
