### ISSUE TITLE
Mock up what an agreement detail page could look like when an agreement is pending, and later executed

### ISSUE THREAD

**Issue by cmajel** [USDAForestService/NRM-Grants-Agreements#219]
**Background**
We identified what we needed to create a proposal and commitment in our last round of research, and we want to identify what a grants management specialist needs to review and add to make a proposal into an executed agreement. This work will explore 
* The information architecture of...
  * A pending proposal that needs to be reviewed by a GMS
  * An agreement that is executed by a GMS and becomes active
* What information a GMS needs to review to execute an agreement
* What information a GMS needs to add to execute an agreement

Scenario assumptions
* A GMS needs to review a proposal
* The proposal has been approved by program
* Program has provided funding information

**We'll know we're done when...**
- [ ] We have a mockup of an agreement details page that can be validated with people who use G&A and guide future engineering work

**Tasks**
- [x] Document GMS needs during review and execution
- [ ] Validate GMS needs with G&A staff
- [x] Create a mockup
- [ ] Share mockup with G&A staff

**Comment by jayrbergjr** [comment]
Assumption should be a fully signed agreement.  But to do testing, we need an agreement to go through.  Many of the fields in nrm are filled in based on the signed agreement. A gms can get many of the fields filled in prior to a signed agreement, but until it is fully signed, you can't fill in everything need to execute.

**Comment by cmajel** [comment]
@jayrbergjr that is helpful! Can you say more about this:

`A gms can get many of the fields filled in prior to a signed agreement, but until it is fully signed, you can't fill in everything need to execute.`

I had thought that a GMS adds data to execute the agreement, and then it goes for signatures. But, this statement makes me wonder if I have things out of order. What are some things that currently GMSs have to wait to fill in until there are signatures?

**Comment by cmajel** [comment]
I've added some notes detailing what[ GMSs do to review a proposal](https://docs.google.com/document/d/1C1jK_01plZ2Xy9CJWi26smPWgxGWfMqF9HNiV8NbVU8/edit#) from `GA-pending` and make it into an agreement that is `GA-executed`

**Comment by cmajel** [comment]
@MelissaBraxton[ I started some notes ](https://app.mural.co/t/gsa6/m/gsa6/1621276440616/11492d54e1410f10eac2ec755a6d0428f19c8ab9)on what the current system's agreement IA looks like at different stages of approval, and what actions / info lives within each tab.

**Comment by cmajel** [comment]
Flagging that this issue is still a good one to pursue, but it needs some adjusting to align with the current workflow hypothesis. Specifically removing the commitment assumptions:

`The commitment information has been approved by program and budget`

**Comment by cmajel** [comment]
I've started working on some light wireframes for this:

* [Figma link](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1123%3A7587)

I expect this will spill into the next sprint as we work through the data flow #326.

@jayrbergjr @MelissaBraxton, this issue probably could have used more refinement based on the current workflow. I'm thinking of this now as what a GMS sees when they do their first review and assign an agreement type/number, and what a Budget approver sees when they are reviewing a PMs funding request. Does that feel like the right scope for this issue right now? If so, I can adjust the description.

A few questions and thoughts that I've encountered as I work on this. These don't need answers now, but surfacing for transparency:
* How do GMSs/BAs express confusion or ask for clarification? What are reasons why something may get rejected or sent back at this stage?
* How async vs linear should this be? Could a GMS get started on provisions while a BA is reviewing funding? Or do they need to wait?
* Can everyone edit everything? Can PMs edit any field? Or do certain roles have edit permissions on certain fields? (Like only GMS can control agreement type, for example, but everyone can edit project description)
* I've been thinking a lot about how we direct people to the actions they need to take while also building IA patterns for an agreement and making information easy to reference. Do we walk people through fields in line that need their attention? Or, create distinct flows for certain actions (assign agreement type and number)

**Comment by cmajel** [comment]
@jayrbergjr @MelissaBraxton I've added some wireframes for review[ in Figma](https://www.figma.com/file/AOWq8IWGSAUGZiqZ1nZSeF/USFS-Grants-and-Agreements-Playground?node-id=1123%3A6967) (pink and purple lines). I tried two versions:

1. Making GMS actions (assigning a type and agreement number) a distinct part of the review flow
2. Embedding fields GMSs need to edit into the form itself, and making this more of a save and continue action

@jayrbergjr what's your preferred channel to review? I can post here, slack, or Teams, or you can view the Figma mock directly.

As I went, a number of questions came up. In addition to the questions in my previous comment, I began to ask:

* Related to edit /read only permissions: How much saving / versioning do we need at different stages? For example, when a GMS starts their review, should that create a new `version` that they can fully edit? 
* How much do we introduce the [face sheet structure](https://drive.google.com/file/d/1uIkBCvYhAKi5P_iRrLMw9HZeddXleRkR/view?usp=sharing) in the UI? I refrained from mimicking it in this proposal review stage, but I did consider if it would be valuable to introduce this structure. How familiar are GMSs with this?
* Would GMSs ever add or remove proposal attachments like SOWs and financial plans? Would they edit them, or are PMs responsible for these edits?

**Comment by jayrbergjr** [comment]
My preference is Teams first, but I do get e-mails from GitHub that I have been trying to keep up with.  As an FYI, when I click the "in Figma" link, I can't get into the system; I get a "File not found" error.

**Comment by cmajel** [comment]
Closing this as we've posted it in teams and we reviewed with @jayrbergjr . There is a summary of this work and draft prototypes [on the wiki](https://github.com/USDAForestService/NRM-Grants-Agreements/wiki/Timeline-of-design-activities#august-2021-reviewing-proposals).
