### ISSUE TITLE
Fix accomplishmentinstrument creation

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#222]
**Background**
In the course of the #189 work, we've learned that the Accomplishment Instrument table has a lot of constraints and things we're not accounting for in our model but will need to. Right now, we cannot save one.

**We'll know we're done when...**
- [ ] DB-level constraints are accounted for in model
- [ ] We've accounted for fields we need to provide values for (cn, ID)
- [ ] We find ai.save() in the code and uncomment it
- [ ] AI instrument is created and saved correctly when it should be.

**Tasks**
- [ ] 
- [ ]

**Comment by tbaxter-18f** [comment]
This is a pretty significant defect. Currently our handling of accomplishment instruments is completely broken (and they're used in agreement creation)

**Comment by neilmb** [comment]
See https://github.com/USDAForestService/NRM-Grants-Agreements/pull/401 for a response to the underlying conceptual issue and closing this as Django-specific.
