### ISSUE TITLE
Figure out "in_instance"

### ISSUE THREAD

**Issue by tbaxter-18f** [USDAForestService/NRM-Grants-Agreements#224]
**Background**
The existing NRM app has a mess of fields like "created_in_instance"  and "modified_in_instance" scattered across the DB tables. We have some loose idea that these refer to different parts of the overall system, but we don't know much about them beyond that.

* Are they still needed at all?
* If so, how do we capture them?

**We'll know we're done when...**
- [ ] Above questions are answered.
- [ ] Based on those answers, fields are removed or are given proper data (or stories are logged to do so
- [ ] Fake instances (like 10602) are removed.

**Tasks**
- [ ] 
- [ ]
