### ISSUE TITLE
Fix search box description in different admin views

### ISSUE THREAD

**Issue by neilmb** [USDAForestService/NRM-Grants-Agreements#230]
**Background**

In the "Users" section of the Django admin, the description above the search box refers to "project title, description, cooperator name, agreement number or application ID" from our Grants and Agreeements search, but it should instead say something like "search by username" when we are under Users.

![Screen Shot 2021-05-13 at 14 29 45](https://user-images.githubusercontent.com/443389/118178241-550bd700-b3f9-11eb-896a-c20a2d41c837.png)
 
The solution is to override the admin changelist_view and pass it in context there, something along the lines of

```python
def changelist_view(self, request, extra_context=None):
        extra_context = extra_context or {}
        extra_context['search_desc'] = "blah blah blah"
        return super().changelist_view(
            request, extra_context=extra_context,
        )
```

**We'll know we're done when...**
- [ ] The search box in the Users section shows a description that is correct for searching for users.

**Tasks**
- [ ] See above for the suggested code change.
- [ ] Let's write a unit test to verify that this is true and that it stays this way.
