### ISSUE TITLE
Technical research spike: investigate leveraging UMA for user role configuration

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#243]
**Background**
As part of M1 v1, we will need to leverage user roles to determine what actions a user can take or what signals they can provide (approvals, executing an agreements, etc). As we understand it, roles can change frequently and can differ based on region. We think it's possible that we could leverage or integrate with UMA. 

The goal of this issue is to understand whether it's feasible to leverage UMA and how it could be done, or if we will need to create a separate user model that leverages eAuth. 

**We'll know we're done when...**
- [ ] We know whether it's possible to leverage UMA for user role configuration in the Django app, or whether we will need to create our own.
- [ ] We have documented our findings.
- [ ] We have created new issues based on what work would be required, or another issue to scope based on the findings.

**Tasks**
- [ ] 
- [ ]

**Comment by allisonnorman** [comment]
@neilmb Feel free to add to this one too

**Comment by tbaxter-18f** [comment]
We will probably have a follow-up issue to connect URM to Django's own user/group config.
