### ISSUE TITLE
Transfer Django prototype from cloud.gov to Skynet

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#246]
**Background**
<Add more!>

**We'll know we're done when...**
- [x] Our Django prototype is running in Skynet. 
- [ ] We've updated technical documentation on the wiki

**Tasks**
- [ ] Create redirect from Cloud (blank html page with a JS redirect?)
- [ ]
