### ISSUE TITLE
Transition GH project board to Zenhub

### ISSUE THREAD

**Issue by allisonnorman** [USDAForestService/NRM-Grants-Agreements#250]
**Background**
Now that we're in the USDA org, we can now use Zenhub! Let's plan this transition.

**We'll know we're done when...**
- [x] The Zenhub kanban board reflects our GH Projects kanban, but better!
- [x] The team has transitioned to using this view for agile ceremonies.

**Tasks**
- [x] Configure the Zenhub board to reflect our current sprint lanes.
- [x] Update the epics and milestones using ZH (convert epics, etc)
- [x] Chat with Jay and make sure he has access and is familiar with the tool. 
- [x] Communicate with the team and flip the switch to using ZH. 
- [x] Remove duplicative labels.
