### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#263]
**Background**

**We'll know we're done when...**
- [x] We have a succinct description of the work for an internal audience
- [x] The README includes path to relevant docs 

**Tasks**
- [x] Draft README
- [x] Circulate for team to review
- [x] Incorporate feedback

**Comment by MelissaBraxton** [comment]
@allisonnorman - I took myself off of this for now so that I can focus on the artifact library. With the work you've done on the onboarding doc, I'm thinking you might be better suited to taking this on if/when you have capacity.

**Comment by allisonnorman** [comment]
I folded this into the onboarding doc. Here's the link: [README 
USFS NRM Grants & Agreements](https://docs.google.com/document/d/1VkuVKqsFI9ojixaAPHaX-jrpUq0HP81Hgf53DUM-nRQ/edit#heading=h.my4hgyykpjmd)
