### ISSUE TITLE
Get cost breakdown of eFG at USDA from USDA COR

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/NRM-Grants-Agreements#50]
**Background**
We want to help USFs better understand the costs of going with a particular vendor solution. To that end, we want to get numbers from USDA and/or census on what they pay

**Acceptance criteria** 
- [ ] We have an example real cost estimate 
- [ ] We've incorporated it into our TCO model

**Tasks**
- [ ] Follow up w/ Census
- [ ] Follow up w/ USDA COR/CO
- [ ] Consider following up with someone who can help us look in agMax

**Definition of done**
- [ ]  Meets acceptance critera

**Comment by allisonnorman** [comment]
@MelissaBraxton Cleaning up the board. Is this still something we're trying to do or should we close?

**Comment by allisonnorman** [comment]
@MelissaBraxton - Should we keep this in the icebox or close as no longer needed? Thanks!

**Comment by MelissaBraxton** [comment]
I think we can close it. Thanks!

Melissa Braxton (she)
Experience Design, 18F
Cell: 425-770-2349
https://18f.gsa.gov/
